## Bank Customer Churn Analysis – Exploratory Data Analysis (EDA)
This project explores **customer churn behavior** using the Bank Churners dataset.
The goal is to identify key factors that influence customer attrition and extract actionable business insights.

## Importing Libraries

In [238]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [239]:
Bank_Churners_df=pd.read_csv(r'C:\Users\Softlaptop\Downloads\archive (3)\BankChurners.csv')
Bank_Churners_df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [240]:
Bank_Churners_df.isna().sum()

CLIENTNUM                                                                                                                             0
Attrition_Flag                                                                                                                        0
Customer_Age                                                                                                                          0
Gender                                                                                                                                0
Dependent_count                                                                                                                       0
Education_Level                                                                                                                       0
Marital_Status                                                                                                                        0
Income_Category                                                                                                                       0
Card_Category                                                                                                                         0
Months_on_book                                                                                                                        0
Total_Relationship_Count                                                                                                              0
Months_Inactive_12_mon                                                                                                                0
Contacts_Count_12_mon                                                                                                                 0
Credit_Limit                                                                                                                          0
Total_Revolving_Bal                                                                                                                   0
Avg_Open_To_Buy                                                                                                                       0
Total_Amt_Chng_Q4_Q1                                                                                                                  0
Total_Trans_Amt                                                                                                                       0
Total_Trans_Ct                                                                                                                        0
Total_Ct_Chng_Q4_Q1                                                                                                                   0
Avg_Utilization_Ratio                                                                                                                 0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1    0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2    0
dtype: int64

No missing values were detected in the dataset.

In [241]:
Bank_Churners_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [242]:
Bank_Churners_df.head(10)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998
5,713061558,Existing Customer,44,M,2,Graduate,Married,$40K - $60K,Blue,36,...,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311,0.000055,0.99994
6,810347208,Existing Customer,51,M,4,Unknown,Married,$120K +,Gold,46,...,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066,0.000123,0.99988
7,818906208,Existing Customer,32,M,0,High School,Unknown,$60K - $80K,Silver,27,...,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048,0.000086,0.99991
8,710930508,Existing Customer,37,M,3,Uneducated,Single,$60K - $80K,Blue,36,...,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113,0.000045,0.99996
9,719661558,Existing Customer,48,M,2,Graduate,Single,$80K - $120K,Blue,36,...,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144,0.000303,0.99970

## Data Cleansing

In [243]:
Bank_Churners_df.drop('CLIENTNUM', axis=1, inplace=True)

In [286]:
Bank_Churners_df.drop('Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1', axis=1, inplace=True)
Bank_Churners_df.drop('Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2', axis=1, inplace=True)

In [287]:
Bank_Churners_df.head()

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Age_Group,Credit_Limit_Group,Trans_Amt_Group
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,...,777,11914,1.335,1144,40-60,1.625,0.061,35–45,High,Very Low
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,...,864,7392,1.541,1291,20-40,3.714,0.105,45–55,High,Very Low
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,...,0,3418,2.594,1887,0-20,2.333,0.000,45–55,Medium,Very Low
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,...,2517,796,1.405,1171,0-20,2.333,0.760,35–45,Low,Very Low
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,...,0,4716,2.175,816,20-40,2.500,0.000,35–45,Medium,Very Low

In [245]:
Bank_Churners_df['Credit_Limit']=Bank_Churners_df['Credit_Limit'].astype(int)
Bank_Churners_df['Avg_Open_To_Buy']=Bank_Churners_df['Avg_Open_To_Buy'].astype(int)

In [288]:
Bank_Churners_df.head(4)

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Age_Group,Credit_Limit_Group,Trans_Amt_Group
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,...,777,11914,1.335,1144,40-60,1.625,0.061,35–45,High,Very Low
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,...,864,7392,1.541,1291,20-40,3.714,0.105,45–55,High,Very Low
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,...,0,3418,2.594,1887,0-20,2.333,0.000,45–55,Medium,Very Low
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,...,2517,796,1.405,1171,0-20,2.333,0.760,35–45,Low,Very Low

## Target Variable Analysis (Churn Distribution)

In [247]:
Bank_Churners_df['Attrition_Flag'].value_counts()

Attrition_Flag
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

In [248]:
fig= px.histogram (
    Bank_Churners_df,
    x= 'Attrition_Flag',
    title= ('Customer Attrition Distribution'),
    color= 'Attrition_Flag',
    width= 700,
    height= 550,
)
fig.show()

In [249]:
Bank_Churners_df['Attrition_Flag'].value_counts(normalize= True)* 100

Attrition_Flag
Existing Customer    83.934038
Attrited Customer    16.065962
Name: proportion, dtype: float64

In [250]:
fig= px.pie(
    Bank_Churners_df,
    names= 'Attrition_Flag',
    title=('Customer Attrition Percentage(%)'),
    width= 500,
    height= 350
)
fig.show()

Only a small percentage of customers have churned, about 16%.

In [251]:
Bank_Churners_df.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

## Age Distribution and Customer Age Groups vs Customer Count and Churn Percentage

In [253]:
import plotly.express as px

px.histogram(
    Bank_Churners_df,
    x="Customer_Age",
    nbins=20,
    title="Distribution of Customer Age",
    color_discrete_sequence=["#636EFA"]
)

In [254]:
Bank_Churners_df["Age_Group"] = pd.cut(
    Bank_Churners_df["Customer_Age"],
    bins=[25, 35, 45, 55, 65, 75],
    labels=["25–35", "35–45", "45–55", "55–65", "65+"]
)

In [255]:
age_summary = Bank_Churners_df.groupby("Age_Group").agg(
    Total_Customers=("Attrition_Flag", "count"),
    Churn_Percentage=("Attrition_Flag",
                      lambda x: (x == "Attrited Customer").mean() * 100)
).reset_index()
age_summary

C:\Users\Softlaptop\AppData\Local\Temp\ipykernel_32224\3675262011.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

  Age_Group  Total_Customers  Churn_Percentage
0     25–35              919         13.275299
1     35–45             3742         16.194548
2     45–55             4135         16.638452
3     55–65             1321         15.821347
4       65+               10         20.000000

In [256]:
import plotly.graph_objects as go

fig = go.Figure()

# عدد العملاء
fig.add_bar(
    x=age_summary["Age_Group"],
    y=age_summary["Total_Customers"],
    name="Number of Customers",
    marker_color="#636EFA"
)

# نسبة churn
fig.add_scatter(
    x=age_summary["Age_Group"],
    y=age_summary["Churn_Percentage"],
    name="Churn Percentage (%)",
    mode="lines+markers",
    yaxis="y2",
    line=dict(color="#EF553B", width=3)
)

fig.update_layout(
    title="Customer Age Groups vs Customer Count and Churn Percentage",
    xaxis_title="Age Group",
    yaxis=dict(title="Number of Customers"),
    yaxis2=dict(
        title="Churn Percentage (%)",
        overlaying="y",
        side="right"
    )
)

fig.show()

Younger customer segments tend to show relatively `higher churn rates` **compared to** `older customers`, suggesting that customer maturity and longer-term financial engagement may contribute to stronger retention behavior.

## Credit Limit Distribution and Churn Percentage VS Credit Limit Groups

In [257]:
px.histogram(
    Bank_Churners_df,
    x="Credit_Limit",
    nbins=30,
    color="Attrition_Flag",
    title="Distribution of Credit Limit",
)

In [258]:
Bank_Churners_df["Credit_Limit_Group"] = pd.qcut(
    Bank_Churners_df["Credit_Limit"],
    5,
    labels=["Very Low", "Low", "Medium", "High", "Very High"]
)

In [259]:
churn_credit= (
    Bank_Churners_df.groupby('Credit_Limit_Group')['Attrition_Flag']
    .value_counts(normalize= True)
    .mul(100)
    .rename('Churn Percentage')
    .reset_index()
)
churn_credit= churn_credit[churn_credit['Attrition_Flag']== 'Attrited Customer']
churn_credit

C:\Users\Softlaptop\AppData\Local\Temp\ipykernel_32224\364642333.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

  Credit_Limit_Group     Attrition_Flag  Churn Percentage
1           Very Low  Attrited Customer         22.606120
3                Low  Attrited Customer         10.913580
5             Medium  Attrited Customer         17.086420
7               High  Attrited Customer         15.308642
9          Very High  Attrited Customer         14.412636

In [260]:
fig = go.Figure()

fig.add_scatter(
    x=churn_credit["Credit_Limit_Group"],
    y=churn_credit["Churn Percentage"],
    name="Churn Percentage (%)",
    mode="lines+markers",
    line=dict(color="#EF553B", width=3)
)

fig.update_layout(
    title="Churn % VS Credit Limit Group",
    xaxis_title="Credit Limit Group",
    yaxis_title="Churn Percentage (%)"
)

fig.show()

In [261]:
Income_Order=[
    'Less than $40K',
    '$40K - $60K',
    '$60K - $80K',
    '$80K - $120K',
    '$120K +',
    'Unknown'
]
fig= px.histogram(
    Bank_Churners_df,
    x= 'Income_Category',
    category_orders={"Income_Category": Income_Order},
    title=('Income Category Distribution'),
    color= 'Attrition_Flag'
)
fig.show()

In [262]:
churn_income = (
    Bank_Churners_df.groupby('Income_Category')['Attrition_Flag']
    .value_counts(normalize=True)
    .mul(100)
    .rename('Churn_Percentage')
    .reset_index()
)

In [263]:
churn_income = churn_income[
    churn_income['Attrition_Flag'] == 'Attrited Customer'
]

In [264]:
fig = px.bar(
    churn_income,
    x='Income_Category',
    y='Churn_Percentage',
    category_orders={'Income_Category': Income_Order},
    title='Churn % VS Income Category',
    color_discrete_sequence=['#EF553B']
)

fig.show()

In [265]:
Bank_Churners_df.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2',
       'Age_Group', 'Credit_Limit_Group'],
      dtype='object')

## Churn Percentage VS Transactions Count

In [266]:
Bank_Churners_df['Total_Trans_Ct']= pd.cut(
    Bank_Churners_df['Total_Trans_Ct'],
    bins=[0,20,40,60,80,100],
    labels=['0-20', '20-40', '40-60', '60-80', '+80']
)

In [267]:
Churn_Trans = (
    Bank_Churners_df.groupby('Total_Trans_Ct')['Attrition_Flag']
    .value_counts(normalize=True)
    .mul(100)
    .rename('Percentage')
    .reset_index()
)
Churn_Trans= Churn_Trans[Churn_Trans['Attrition_Flag']== 'Attrited Customer']

C:\Users\Softlaptop\AppData\Local\Temp\ipykernel_32224\3151971763.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [268]:
px.bar(
    Churn_Trans,
    x="Total_Trans_Ct",
    y='Percentage',
    barmode= 'group',
    title="Churn % VS Transaction Count",
    color_discrete_sequence=['#EF553B'],
    width= 800,
    height=550
)

## Transaction Amount Distribution and Churn Percentage VS Transactions Amount Group

In [269]:
Bank_Churners_df['Trans_Amt_Group'] = pd.cut(
    Bank_Churners_df['Total_Trans_Amt'],
    bins=5,
    labels=[
        "Very Low",
        "Low",
        "Medium",
        "High",
         "Very High"
    ]
)

In [270]:
fig= px.histogram(
    Bank_Churners_df,
    x= 'Trans_Amt_Group',
    title= ('Transaction Amount Distribution'),
    nbins= 30,
    color= 'Attrition_Flag',
    width= 800,
    height= 550
)
fig.update_traces(
    marker_line_width= .5
)
fig.show()

In [271]:
churn_trans_amount= (
    Bank_Churners_df.groupby('Trans_Amt_Group')['Attrition_Flag']
    .value_counts(normalize=True)
    .mul(100)
    .rename('Churn Percentage')
    .reset_index()
)
churn_trans_amount= churn_trans_amount[churn_trans_amount['Attrition_Flag']== 'Attrited Customer']

C:\Users\Softlaptop\AppData\Local\Temp\ipykernel_32224\30550859.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [272]:
fig = px.bar(
    churn_trans_amount,
    x="Trans_Amt_Group",
    y="Churn Percentage",
    title="Churn % VS Transaction Amount",
    color_discrete_sequence=['#EF553B'],
    width= 800,
    height=550
)

fig.show()

Churners_Count = Bank_Churners_df[
    Bank_Churners_df['Attrition_Flag'] == 'Attrited Customer']['Trans_Amt_Group'].value_counts().reset_index()

Churners_Count.columns = ['Trans_Amt_Group', 'Churners_Count']

px.bar(
    Churners_Count,
    x='Trans_Amt_Group',
    y='Churners_Count',
    title='Churners Count VS Transaction Amount',
    color_discrete_sequence=["#FFA999"],
    width= 800,
    height=550
)

Customers in the **Medium transaction amount group have the highest churn rate**, indicating a higher likelihood of attrition compared to other groups.

In [273]:
Bank_Churners_df.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2',
       'Age_Group', 'Credit_Limit_Group', 'Trans_Amt_Group'],
      dtype='object')

## Churn Percentage VS Number of Bank Relationships

In [274]:
churn_relationships= (
    Bank_Churners_df.groupby('Total_Relationship_Count')['Attrition_Flag']
    .value_counts(normalize= True)
    .mul(100)
    .rename('Churn Percentage')
    .reset_index()
)
churn_relationships= churn_relationships[churn_relationships['Attrition_Flag']== 'Attrited Customer']

In [275]:
fig = px.bar(
    churn_relationships,
    x="Total_Relationship_Count",
    y="Churn Percentage",
    title="Churn % vs Number of Bank Relationships",
    color_discrete_sequence=['#EF553B'],
    width= 800,
    height=550
)

fig.show()

Customers with **fewer banking relationships** show significantly **higher churn rates** compared to customers with **multiple relationships**. 
This suggests that increasing cross-selling opportunities may improve customer retention.

In [276]:
Bank_Churners_df.head()

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2,Age_Group,Credit_Limit_Group,Trans_Amt_Group
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,...,1.335,1144,40-60,1.625,0.061,0.000093,0.99991,35–45,High,Very Low
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,...,1.541,1291,20-40,3.714,0.105,0.000057,0.99994,45–55,High,Very Low
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,...,2.594,1887,0-20,2.333,0.000,0.000021,0.99998,45–55,Medium,Very Low
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,...,1.405,1171,0-20,2.333,0.760,0.000134,0.99987,35–45,Low,Very Low
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,...,2.175,816,20-40,2.500,0.000,0.000022,0.99998,35–45,Medium,Very Low

In [277]:
churn_marital_status= (
    Bank_Churners_df.groupby('Marital_Status')['Attrition_Flag']
    .value_counts(normalize= True)
    .mul(100)
    .rename('Churn Percentage')
    .reset_index()
)
churn_marital_status= churn_marital_status[churn_marital_status['Attrition_Flag']== 'Attrited Customer']

In [278]:
churn_marital_status

  Marital_Status     Attrition_Flag  Churn Percentage
1       Divorced  Attrited Customer         16.176471
3        Married  Attrited Customer         15.126947
5         Single  Attrited Customer         16.941415
7        Unknown  Attrited Customer         17.222964

In [279]:
fig = px.bar(
    churn_marital_status,
    x="Marital_Status",
    y="Churn Percentage",
    title="Churn % vs Marital Status",
    color_discrete_sequence=['#EF553B']
)

fig.show()

## Churn Percentage VS Card Category

In [280]:
churn_card_category= (
    Bank_Churners_df.groupby('Card_Category')['Attrition_Flag']
    .value_counts(normalize= True)
    .mul(100)
    .rename('Churn Percentage')
    .reset_index()
)
churn_card_category= churn_card_category[churn_card_category['Attrition_Flag']== 'Attrited Customer']

In [281]:
fig = px.bar(
    churn_card_category,
    x="Card_Category",
    y="Churn Percentage",
    color= 'Card_Category',
    title="Churn % vs Card Category",
    color_discrete_map={
        'Blue': '#636EFA',
        'Gold': "#FD6621",
        'Platinum': "#7E050F",
        'Silver': "#227B04"
    },
    width= 800,
    height=550
)

fig.show()

Customers holding `Platinum` cards exhibit the **highest churn rate among all card categories**, `indicating a potential retention risk within this premium segment. `

This may suggest unmet expectations regarding service value, benefits, or engagement compared to other card tiers. 

In contrast, `Silver` and `Blue` cardholders show relatively **lower churn rates**, reflecting more stable retention behavior.

These findings highlight the importance of reviewing benefit structures and engagement strategies specifically for high-tier cardholders to improve customer loyalty.

In [282]:
Bank_Churners_df

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2,Age_Group,Credit_Limit_Group,Trans_Amt_Group
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,...,1.335,1144,40-60,1.625,0.061,0.000093,0.999910,35–45,High,Very Low
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,...,1.541,1291,20-40,3.714,0.105,0.000057,0.999940,45–55,High,Very Low
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,...,2.594,1887,0-20,2.333,0.000,0.000021,0.999980,45–55,Medium,Very Low
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,...,1.405,1171,0-20,2.333,0.760,0.000134,0.999870,35–45,Low,Very Low
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,...,2.175,816,20-40,2.500,0.000,0.000022,0.999980,35–45,Medium,Very Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,...,0.703,15476,NaN,0.857,0.462,0.000191,0.999810,45–55,Medium,Very High
10123,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,...,0.804,8764,60-80,0.683,0.511,0.995270,0.004729,35–45,Medium,Medium
10124,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,...,0.819,10291,40-60,0.818,0.000,0.997880,0.002118,35–45,Medium,Medium
10125,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,...,0.535,8395,60-80,0.722,0.000,0.996710,0.003294,25–35,Medium,Medium
10126,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,...,0.703,10294,60-80,0.649,0.189,0.996620,0.003377,35–45,High,Medium

## Inactive 12 Months Distribution and Inactive Months vs Customer Count and Churn Percentage

In [283]:
px.histogram(
    Bank_Churners_df,
    x="Months_Inactive_12_mon",
    title="Distribution of Inactive Months in the Last 12 Months",
    color_discrete_sequence=["#636EFA"]
)

The majority of customers fall `within 2–3 inactive months`, while extended inactivity `(4+ months)` is relatively rare and may signal potential disengagement risk.

Although most customers remain `inactive for only 2–3 months`, higher inactivity durations should be monitored closely as they may represent early warning signals of potential customer attrition.

In [284]:
inactive_summary = Bank_Churners_df.groupby('Months_Inactive_12_mon').agg(
    Total_Customers=('Attrition_Flag','count'),
    Churn_Percentage=('Attrition_Flag', lambda x: (x=='Attrited Customer').mean()*100)
).reset_index()

inactive_summary

   Months_Inactive_12_mon  Total_Customers  Churn_Percentage
0                       0               29         51.724138
1                       1             2233          4.478280
2                       2             3282         15.386959
3                       3             3846         21.476859
4                       4              435         29.885057
5                       5              178         17.977528
6                       6              124         15.322581

In [285]:
import plotly.graph_objects as go

fig = go.Figure()

# Bar chart لعدد العملاء
fig.add_bar(
    x=inactive_summary["Months_Inactive_12_mon"],
    y=inactive_summary["Total_Customers"],
    name="Number of Customers",
    marker_color="#636EFA"
)

# Line chart لنسبة churn
fig.add_scatter(
    x=inactive_summary["Months_Inactive_12_mon"],
    y=inactive_summary["Churn_Percentage"],
    name="Churn Percentage (%)",
    mode="lines+markers",
    yaxis="y2",
    line=dict(color="#EF553B", width=3)
)

# إعداد المحور الثاني
fig.update_layout(
    title="Inactive Months vs Customer Count and Churn Percentage",
    xaxis_title="Months Inactive (Last 12 Months)",
    yaxis=dict(title="Number of Customers"),
    yaxis2=dict(
        title="Churn Percentage (%)",
        overlaying="y",
        side="right"
    ),
    legend=dict(x=0.01, y=0.99)
)

fig.show()

Although customers with `zero inactive months` show a relatively `high churn percentage`, **the small sample size in this group reduces reliability**. 

Churn probability increases noticeably `after 3 months of inactivity`, indicating that extended inactivity is a `strong early warning signal of potential customer attrition` and should trigger proactive retention strategies.